<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <NoWarn>$(NoWarn);1591;NETSDK1138</NoWarn>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Microsoft.AspNetCore.Razor.Language\ComponentResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ComponentResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Microsoft.AspNetCore.Razor.Language\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
