using System;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Razor.Language;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Socotra.Razor;

namespace Socotra.Generator;

[Generator]
public sealed class RazorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var razorFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase));

        context.RegisterSourceOutput(razorFiles.Combine(context.AnalyzerConfigOptionsProvider), static (spc, pair) =>
        {
            var file = pair.Left;
            var options = pair.Right.GlobalOptions;
            options.TryGetValue("build_property.projectdir", out var projectDir);
            options.TryGetValue("build_property.rootnamespace", out var rootNamespace);

            var text = file.GetText(spc.CancellationToken)?.ToString();
            if (text is null)
            {
                return;
            }

            var localPath = LocalPath(file.Path, projectDir);
            var className = Path.GetFileNameWithoutExtension(file.Path);
            var ns = FindNamespace(text) ?? DeriveNamespace(Path.GetDirectoryName(localPath), rootNamespace);
            if (string.IsNullOrEmpty(ns))
            {
                return;
            }

            var document = RazorProcessor.GenerateFromSource(text, file.Path, ns!);
            foreach (var diagnostic in document.Diagnostics)
            {
                spc.ReportDiagnostic(ToDiagnostic(diagnostic));
            }

            var hash = (uint)localPath.GetHashCode();
            spc.AddSource($"{className}_{hash:x8}.razor.g.cs", "#nullable restore\n" + document.GeneratedCode);
            spc.AddSource($"{className}_{hash:x8}.socotra.g.cs", $$"""
                // <auto-generated />
                namespace {{ns}}
                {
                    [global::Socotra.ClassFileLocation("{{localPath}}")]
                    public partial class {{className}}
                    {
                    }
                }
                """);
        });
    }

    private static Diagnostic ToDiagnostic(RazorDiagnostic diagnostic)
    {
        var span = diagnostic.Span;
        var severity = diagnostic.Severity == RazorDiagnosticSeverity.Error ? DiagnosticSeverity.Error : DiagnosticSeverity.Warning;
        var descriptor = new DiagnosticDescriptor(diagnostic.Id, "Razor", "{0}", "Razor", severity, isEnabledByDefault: true);
        var start = new LinePosition(span.LineIndex, span.CharacterIndex);
        var end = new LinePosition(span.LineIndex + span.LineCount, span.EndCharacterIndex);
        var location = Location.Create(span.FilePath, new TextSpan(span.AbsoluteIndex, span.Length), new LinePositionSpan(start, end));
        return Diagnostic.Create(descriptor, location, diagnostic.GetMessage(null));
    }

    private static string LocalPath(string path, string? projectDir)
    {
        var full = path.Replace('\\', '/');
        if (!string.IsNullOrEmpty(projectDir))
        {
            var root = projectDir!.Replace('\\', '/').TrimEnd('/');
            if (full.StartsWith(root, StringComparison.OrdinalIgnoreCase))
            {
                full = full.Substring(root.Length);
            }
        }

        return full.TrimStart('/');
    }

    private static string? FindNamespace(string text)
    {
        var match = Regex.Match(text, @"^\s*@namespace\s+([\w\.]+)", RegexOptions.Multiline);
        return match.Success ? match.Groups[1].Value : null;
    }

    private static string? DeriveNamespace(string? directory, string? rootNamespace)
    {
        if (string.IsNullOrEmpty(rootNamespace))
        {
            return null;
        }

        var folders = (directory ?? "").Replace('\\', '/').Split(['/'], StringSplitOptions.RemoveEmptyEntries)
            .Where(folder => !char.IsDigit(folder[0]) && !folder.Contains(" ") && !folder.Contains("-") && !folder.Contains(":") && folder != "." && folder != "..");
        return string.Join(".", new[] { rootNamespace! }.Concat(folders));
    }
}
