<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System.Numerics" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Svg.Skia" Version="2.0.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.AspNetCore.Components\Microsoft.AspNetCore.Components.csproj" />
    <ProjectReference Include="..\Socotra.Layout\Socotra.Layout.csproj" />
    <ProjectReference Include="..\Topten.RichTextKit\Topten.RichTextKit.csproj" />
  </ItemGroup>

</Project>
